/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini_proj;

import javax.swing.JOptionPane;
import org.json.simple.JSONObject;
import org.json.simple.JSONArray;
import java.io.FileWriter;
import java.io.FileReader;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author Chinmay
 */
public class multiple_options_page extends javax.swing.JFrame {

    /**
     * Creates new form multiple_options_page
     */
    public multiple_options_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EXPRESS DISPATCH");
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setPreferredSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Snap ITC", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("What would you like to shop??");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 20, 466, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/laprop_img3.jpeg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(51, 98, 180, 121);

        jLabel4.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tshirt_img.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(760, 350, 120, 170);

        jLabel5.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/shoes_img.jpeg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(700, 90, 200, 140);

        jLabel6.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("T-SHIRT  Rs1,499");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(730, 560, 170, 19);

        jLabel7.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("HEADPHONES Rs899");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(390, 560, 200, 19);

        jLabel8.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("LAPTOP  Rs 39,999");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 240, 195, 38);

        jLabel10.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("SMART WATCH RS4,999");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 560, 220, 19);

        jLabel14.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("SHOES Rs2,999");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(720, 250, 150, 19);

        jLabel15.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/headphones_img2.jpeg"))); // NOI18N
        jLabel15.setToolTipText("");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(400, 360, 170, 170);

        jLabel16.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/smart_watch_img.jpeg"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(60, 360, 170, 170);

        jLabel17.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("CRICKET BAT Rs3,999");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(360, 240, 221, 50);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cricket_bat_img.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(400, 90, 107, 121);

        jButton1.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add_to_cart_img2.jpg"))); // NOI18N
        jButton1.setText("BUY NOW");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 290, 190, 30);

        jButton2.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add_to_cart_img2.jpg"))); // NOI18N
        jButton2.setText("BUY NOW");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(360, 290, 200, 33);

        jButton3.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add_to_cart_img2.jpg"))); // NOI18N
        jButton3.setText("BUY NOW");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(50, 600, 200, 33);

        jButton4.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add_to_cart_img2.jpg"))); // NOI18N
        jButton4.setText("BUY NOW");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(380, 600, 210, 33);

        jButton5.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add_to_cart_img2.jpg"))); // NOI18N
        jButton5.setText("BUY NOW");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(710, 600, 210, 33);

        jButton6.setFont(new java.awt.Font("Snap ITC", 3, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add_to_cart_img2.jpg"))); // NOI18N
        jButton6.setText("BUY NOW");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(690, 290, 220, 33);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/multi_option_page_img1.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1000, 740);

        jMenu1.setText("LOG OUT");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logout.jpg"))); // NOI18N
        jMenuItem1.setText("LOG OUT");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //on buying headphones
        
        String rname=JOptionPane.showInputDialog(null,"Enter Reciepant Name");
        String r_x_coordinate=JOptionPane.showInputDialog(null,"Enter Reciepant X coordinate");
        String r_y_coordinate=JOptionPane.showInputDialog(null,"Enter Reciepant Y coordinate");
         
        JSONObject non_spl_customer_obj=new JSONObject();
        JSONArray non_spl_customer_jrr=new JSONArray();
        JSONParser Jp=new JSONParser();
         
        try{
            FileReader non_spl_customer_file=new FileReader("rdeliverynonspecialcustomerfile.json");
            non_spl_customer_jrr=(JSONArray)Jp.parse(non_spl_customer_file); 
        }
        catch(Exception e1)
        {
            JOptionPane.showMessageDialog(null,"ERROR OCCURED WHILE READING rdeliverynonspecialcustomerfile FILE");
        }
         
        non_spl_customer_obj.put("reciepant name",rname);
        non_spl_customer_obj.put("x coordinate",r_x_coordinate);
        non_spl_customer_obj.put("y coordinate",r_y_coordinate);
        non_spl_customer_obj.put("item purchased","Headphones");
        
        non_spl_customer_jrr.add(non_spl_customer_obj);
        
        try{
            FileWriter non_spl_customer_file=new FileWriter("rdeliverynonspecialcustomerfile.json");
            non_spl_customer_file.write(non_spl_customer_jrr.toJSONString());
            non_spl_customer_file.close();
        }
        catch(Exception ex1)
        {
            JOptionPane.showMessageDialog(null, "Error occured while writing");
        }
        
        JOptionPane.showMessageDialog(null,"YAY!Your order has been placed!");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //on buying cricket bat
        
        String rname=JOptionPane.showInputDialog(null,"Enter Reciepant Name");
        String r_x_coordinate=JOptionPane.showInputDialog(null,"Enter Reciepant X coordinate");
        String r_y_coordinate=JOptionPane.showInputDialog(null,"Enter Reciepant Y coordinate");
         
        JSONObject non_spl_customer_obj=new JSONObject();
        JSONArray non_spl_customer_jrr=new JSONArray();
        JSONParser Jp=new JSONParser();
         
        try{
            FileReader non_spl_customer_file=new FileReader("rdeliverynonspecialcustomerfile.json");
            non_spl_customer_jrr=(JSONArray)Jp.parse(non_spl_customer_file); 
        }
        catch(Exception e1)
        {
            JOptionPane.showMessageDialog(null,"ERROR OCCURED WHILE READING rdeliverynonspecialcustomerfile FILE");
        }
         
        non_spl_customer_obj.put("reciepant name",rname);
        non_spl_customer_obj.put("x coordinate",r_x_coordinate);
        non_spl_customer_obj.put("y coordinate",r_y_coordinate);
        non_spl_customer_obj.put("item purchased","Cricket Bat");
        
        non_spl_customer_jrr.add(non_spl_customer_obj);
        
        try{
            FileWriter non_spl_customer_file=new FileWriter("rdeliverynonspecialcustomerfile.json");
            non_spl_customer_file.write(non_spl_customer_jrr.toJSONString());
            non_spl_customer_file.close();
        }
        catch(Exception ex1)
        {
            JOptionPane.showMessageDialog(null, "Error occured while writing");
        }
        
        JOptionPane.showMessageDialog(null,"YAY!Your order has been placed!");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //on clicking buy laptop
        
         String rname=JOptionPane.showInputDialog(null,"Enter Reciepant Name");
         String r_x_coordinate=JOptionPane.showInputDialog(null,"Enter Reciepant X coordinate");
         String r_y_coordinate=JOptionPane.showInputDialog(null,"Enter Reciepant Y coordinate");
         
         JSONObject non_spl_customer_obj=new JSONObject();
         JSONArray non_spl_customer_jrr=new JSONArray();
         JSONParser Jp=new JSONParser();
         
        try{
            FileReader non_spl_customer_file=new FileReader("rdeliverynonspecialcustomerfile.json");
            non_spl_customer_jrr=(JSONArray)Jp.parse(non_spl_customer_file); 
        }
        catch(Exception e1)
        {
            JOptionPane.showMessageDialog(null,"ERROR OCCURED WHILE READING rdeliverynonspecialcustomerfile FILE");
        }
         
        non_spl_customer_obj.put("reciepant name",rname);
        non_spl_customer_obj.put("x coordinate",r_x_coordinate);
        non_spl_customer_obj.put("y coordinate",r_y_coordinate);
        non_spl_customer_obj.put("item purchased","Laptop");
        
        non_spl_customer_jrr.add(non_spl_customer_obj);
        
        try{
            FileWriter non_spl_customer_file=new FileWriter("rdeliverynonspecialcustomerfile.json");
            non_spl_customer_file.write(non_spl_customer_jrr.toJSONString());
            non_spl_customer_file.close();
        }
        catch(Exception ex1)
        {
            JOptionPane.showMessageDialog(null, "Error occured while writing");
        }
        
        JOptionPane.showMessageDialog(null,"YAY!Your order has been placed!");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //on buying shoes
        
        String rname=JOptionPane.showInputDialog(null,"Enter Reciepant Name");
        String r_x_coordinate=JOptionPane.showInputDialog(null,"Enter Reciepant X coordinate");
        String r_y_coordinate=JOptionPane.showInputDialog(null,"Enter Reciepant Y coordinate");
         
        JSONObject non_spl_customer_obj=new JSONObject();
        JSONArray non_spl_customer_jrr=new JSONArray();
        JSONParser Jp=new JSONParser();
         
        try{
            FileReader non_spl_customer_file=new FileReader("rdeliverynonspecialcustomerfile.json");
            non_spl_customer_jrr=(JSONArray)Jp.parse(non_spl_customer_file); 
        }
        catch(Exception e1)
        {
            JOptionPane.showMessageDialog(null,"ERROR OCCURED WHILE READING rdeliverynonspecialcustomerfile FILE");
        }
         
        non_spl_customer_obj.put("reciepant name",rname);
        non_spl_customer_obj.put("x coordinate",r_x_coordinate);
        non_spl_customer_obj.put("y coordinate",r_y_coordinate);
        non_spl_customer_obj.put("item purchased","Shoes");
        
        non_spl_customer_jrr.add(non_spl_customer_obj);
        
        try{
            FileWriter non_spl_customer_file=new FileWriter("rdeliverynonspecialcustomerfile.json");
            non_spl_customer_file.write(non_spl_customer_jrr.toJSONString());
            non_spl_customer_file.close();
        }
        catch(Exception ex1)
        {
            JOptionPane.showMessageDialog(null, "Error occured while writing");
        }
        
        JOptionPane.showMessageDialog(null,"YAY!Your order has been placed!");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //on buying smart watch
        
        String rname=JOptionPane.showInputDialog(null,"Enter Reciepant Name");
        String r_x_coordinate=JOptionPane.showInputDialog(null,"Enter Reciepant X coordinate");
        String r_y_coordinate=JOptionPane.showInputDialog(null,"Enter Reciepant Y coordinate");
         
        JSONObject non_spl_customer_obj=new JSONObject();
        JSONArray non_spl_customer_jrr=new JSONArray();
        JSONParser Jp=new JSONParser();
         
        try{
            FileReader non_spl_customer_file=new FileReader("rdeliverynonspecialcustomerfile.json");
            non_spl_customer_jrr=(JSONArray)Jp.parse(non_spl_customer_file); 
        }
        catch(Exception e1)
        {
            JOptionPane.showMessageDialog(null,"ERROR OCCURED WHILE READING rdeliverynonspecialcustomerfile FILE");
        }
         
        non_spl_customer_obj.put("reciepant name",rname);
        non_spl_customer_obj.put("x coordinate",r_x_coordinate);
        non_spl_customer_obj.put("y coordinate",r_y_coordinate);
        non_spl_customer_obj.put("item purchased","Smart Watch");
        
        non_spl_customer_jrr.add(non_spl_customer_obj);
        
        try{
            FileWriter non_spl_customer_file=new FileWriter("rdeliverynonspecialcustomerfile.json");
            non_spl_customer_file.write(non_spl_customer_jrr.toJSONString());
            non_spl_customer_file.close();
        }
        catch(Exception ex1)
        {
            JOptionPane.showMessageDialog(null, "Error occured while writing");
        }
        
        JOptionPane.showMessageDialog(null,"YAY!Your order has been placed!");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //on buying t shirt
        
        String rname=JOptionPane.showInputDialog(null,"Enter Reciepant Name");
        String r_x_coordinate=JOptionPane.showInputDialog(null,"Enter Reciepant X coordinate");
        String r_y_coordinate=JOptionPane.showInputDialog(null,"Enter Reciepant Y coordinate");
         
        JSONObject non_spl_customer_obj=new JSONObject();
        JSONArray non_spl_customer_jrr=new JSONArray();
        JSONParser Jp=new JSONParser();
         
        try{
            FileReader non_spl_customer_file=new FileReader("rdeliverynonspecialcustomerfile.json");
            non_spl_customer_jrr=(JSONArray)Jp.parse(non_spl_customer_file); 
        }
        catch(Exception e1)
        {
            JOptionPane.showMessageDialog(null,"ERROR OCCURED WHILE READING rdeliverynonspecialcustomerfile FILE");
        }
         
        non_spl_customer_obj.put("reciepant name",rname);
        non_spl_customer_obj.put("x coordinate",r_x_coordinate);
        non_spl_customer_obj.put("y coordinate",r_y_coordinate);
        non_spl_customer_obj.put("item purchased","TShirt");
        
        non_spl_customer_jrr.add(non_spl_customer_obj);
        
        try{
            FileWriter non_spl_customer_file=new FileWriter("rdeliverynonspecialcustomerfile.json");
            non_spl_customer_file.write(non_spl_customer_jrr.toJSONString());
            non_spl_customer_file.close();
        }
        catch(Exception ex1)
        {
            JOptionPane.showMessageDialog(null, "Error occured while writing");
        }
        
        JOptionPane.showMessageDialog(null,"YAY!Your order has been placed!");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(multiple_options_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(multiple_options_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(multiple_options_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(multiple_options_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new multiple_options_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
