/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mini_proj;

import javax.swing.JOptionPane;
import org.json.simple.JSONObject;
import org.json.simple.JSONArray;
import java.io.FileWriter;
import java.io.FileReader;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author Chinmay
 */
public class sign_up_page extends javax.swing.JFrame {
    JSONArray jrr=new JSONArray();

    /**
     * Creates new form sign_up_page
     */
    public sign_up_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        setname = new javax.swing.JTextField();
        JLabelpassword = new javax.swing.JLabel();
        setpassword = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        conf_password = new javax.swing.JPasswordField();
        setemail = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        date = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        splcustomer = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        x_coordinate = new javax.swing.JTextField();
        y_coordinate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EXPRESS DISPATCH-SIGN UP");
        setPreferredSize(new java.awt.Dimension(615, 575));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("SET USERNAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 80, 150, 21);

        jLabel2.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("SET PASSWORD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 140, 140, 21);

        jLabel3.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("EMAIL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 210, 100, 21);

        jLabel4.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("GENDER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 270, 90, 21);

        jLabel5.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("DOB");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 270, 40, 21);

        jLabel6.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("ADDRESS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 340, 90, 21);

        jLabel10.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("NAME");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 20, 70, 30);

        setname.setBackground(new java.awt.Color(200, 200, 200));
        setname.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        getContentPane().add(setname);
        setname.setBounds(30, 50, 290, 20);

        JLabelpassword.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        JLabelpassword.setForeground(new java.awt.Color(240, 240, 240));
        JLabelpassword.setText("CONFIRM PASSWORD");
        getContentPane().add(JLabelpassword);
        JLabelpassword.setBounds(310, 140, 200, 21);

        setpassword.setBackground(new java.awt.Color(200, 200, 200));
        getContentPane().add(setpassword);
        setpassword.setBounds(30, 160, 250, 22);

        username.setBackground(new java.awt.Color(200, 200, 200));
        username.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        getContentPane().add(username);
        username.setBounds(30, 100, 290, 20);

        conf_password.setBackground(new java.awt.Color(200, 200, 200));
        getContentPane().add(conf_password);
        conf_password.setBounds(310, 160, 260, 22);

        setemail.setBackground(new java.awt.Color(200, 200, 200));
        setemail.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        getContentPane().add(setemail);
        setemail.setBounds(30, 230, 250, 20);

        gender.setBackground(new java.awt.Color(200, 200, 200));
        gender.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER" }));
        gender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        getContentPane().add(gender);
        gender.setBounds(30, 300, 80, 20);

        date.setBackground(new java.awt.Color(200, 200, 200));
        date.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        getContentPane().add(date);
        date.setBounds(170, 300, 63, 20);

        month.setBackground(new java.awt.Color(200, 200, 200));
        month.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        getContentPane().add(month);
        month.setBounds(250, 300, 63, 20);

        year.setBackground(new java.awt.Color(200, 200, 200));
        year.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        getContentPane().add(year);
        year.setBounds(330, 300, 63, 20);

        address.setBackground(new java.awt.Color(200, 200, 200));
        address.setColumns(20);
        address.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        address.setRows(5);
        jScrollPane1.setViewportView(address);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 370, 260, 50);

        jButton1.setBackground(new java.awt.Color(119, 51, 255));
        jButton1.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setText("SUBMIT");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 440, 75, 23);

        jButton2.setBackground(new java.awt.Color(119, 51, 255));
        jButton2.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("RESET");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 440, 67, 23);

        jLabel8.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("SPECIAL CUSTOMER?");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(310, 210, 200, 20);

        splcustomer.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        splcustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "YES" }));
        splcustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        splcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splcustomerActionPerformed(evt);
            }
        });
        getContentPane().add(splcustomer);
        splcustomer.setBounds(310, 230, 70, 20);

        jLabel7.setFont(new java.awt.Font("Courier New", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("COORDINATES");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 340, 140, 21);

        jLabel9.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("X");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(320, 370, 30, 17);

        jLabel11.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Y");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(420, 370, 43, 17);

        x_coordinate.setBackground(new java.awt.Color(200, 200, 200));
        getContentPane().add(x_coordinate);
        x_coordinate.setBounds(320, 390, 63, 20);

        y_coordinate.setBackground(new java.awt.Color(200, 200, 200));
        getContentPane().add(y_coordinate);
        y_coordinate.setBounds(420, 390, 63, 22);

        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sign_up_page.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 620, 510);

        jMenu1.setText("HOME");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home.jpg"))); // NOI18N
        jMenuItem1.setText("HOME");
        jMenuItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("LOG IN");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N

        jMenuItem3.setFont(new java.awt.Font("Courier New", 3, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sign_in.png"))); // NOI18N
        jMenuItem3.setText("LOG IN");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //on clicking submit
        
        int st=1;
        int i=0;
        
        JSONObject username_obj=new JSONObject();
        JSONObject password_obj=new JSONObject();
        JSONObject spl_customer_obj=new JSONObject();
        JSONObject other_details_obj=new JSONObject();
        
        JSONArray username_jrr=new JSONArray();
        JSONArray password_jrr=new JSONArray();
        JSONArray spl_customer_jrr=new JSONArray();
        JSONArray other_details_jrr=new JSONArray();
        
        JSONParser Jp1=new JSONParser();
        JSONParser Jp2=new JSONParser();
        JSONParser Jp3=new JSONParser();
        JSONParser Jp4=new JSONParser();
        
        try{
            FileReader username_file=new FileReader("usernamefile.json");
            username_jrr=(JSONArray)Jp1.parse(username_file); 
        }
        catch(Exception e1)
        {
            JOptionPane.showMessageDialog(null,"ERROR OCCURED WHILE READING USERNAME FILE");
        }
        
        try{
            FileReader password_file=new FileReader("passwordfile.json");
            password_jrr=(JSONArray)Jp2.parse(password_file); 
        }
        catch(Exception e2)
        {
            JOptionPane.showMessageDialog(null,"ERROR OCCURED WHILE READING PASSWORD FILE");
        }
        
        
        try{
            FileReader spl_customer_file=new FileReader("specialcustomerfile.json");
            spl_customer_jrr=(JSONArray)Jp4.parse(spl_customer_file); 
        }
        catch(Exception e4)
        {
            JOptionPane.showMessageDialog(null,"ERROR OCCURED WHILE READING spl customer FILE");
        }
        
        
        
        try{
            FileReader other_details_file=new FileReader("otherdetailsfile.json");
            other_details_jrr=(JSONArray)Jp3.parse(other_details_file); 
        }
        catch(Exception e3)
        {
            JOptionPane.showMessageDialog(null,"ERROR OCCURED WHILE READING OTHER DETAIS FILE");
        }
        
        
        
        username_obj.put("username", username.getText());
        int usernames_size=username_jrr.size();
        
        password_obj.put("password", setpassword.getText());
        
        spl_customer_obj.put("special_customer",splcustomer.getSelectedItem());
        
        
        other_details_obj.put("name",setname.getText());
        other_details_obj.put("email",setemail.getText());
        other_details_obj.put("gender",gender.getSelectedItem());
        other_details_obj.put("date",date.getText());
        other_details_obj.put("month",month.getText());
        other_details_obj.put("year",year.getText());
        other_details_obj.put("address",address.getText());
        other_details_obj.put("x coordinate",x_coordinate.getText());
        other_details_obj.put("y coordinate",y_coordinate.getText());
        
        
        
        for(i=0;i<usernames_size;i++)
        {
            if(username_obj.equals(username_jrr.get(i)))
            {
                st=0;
                break;
            }
        }
        
        if(setpassword.getText().equals("") || setname.getText().equals("") || username.getText().equals("") || conf_password.getText().equals("") || setemail.getText().equals("") || address.getText().equals("") || x_coordinate.getText().equals("") || y_coordinate.getText().equals("") || date.getText().equals("") || month.getText().equals("") || year.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter all the fields");
        }
        else if(!(setpassword.getText().equals(conf_password.getText())))
        {
            JOptionPane.showMessageDialog(null, "Please confirm with the right password");
        }
        else if(st==1)
        {
            
            username_jrr.add(username_obj);
            password_jrr.add(password_obj);
            other_details_jrr.add(other_details_obj);
            spl_customer_jrr.add(spl_customer_obj);
        
            try{
                FileWriter username_file=new FileWriter("usernamefile.json");
                username_file.write(username_jrr.toJSONString());
                username_file.close();
            }
            catch(Exception ex1)
            {
                JOptionPane.showMessageDialog(null, "Error occured while fetching");
            }
        
            try{
                FileWriter password_file=new FileWriter("passwordfile.json");
                password_file.write(password_jrr.toJSONString());
                password_file.close();
            }
            catch(Exception ex2)
            {
                JOptionPane.showMessageDialog(null, "Error occured while fetching");
            }
            
            try{
                FileWriter spl_customer_file=new FileWriter("specialcustomerfile.json");
                spl_customer_file.write(spl_customer_jrr.toJSONString());
                spl_customer_file.close();
            }
            catch(Exception ex1)
            {
                JOptionPane.showMessageDialog(null, "Error occured while fetching");
            }
        
            try{
                FileWriter other_details_file=new FileWriter("otherdetailsfile.json");
                other_details_file.write(other_details_jrr.toJSONString());
                other_details_file.close();
            }
            catch(Exception ex2)
            {
                JOptionPane.showMessageDialog(null, "Error occured while fetching");
            }

            JOptionPane.showMessageDialog(null,"Sign up successful");
            
            
        
            new sign_in_page().setVisible(true);
            
            this.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Oops! Username already taken.Try another one!");
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //on clicking reset
        
        setname.setText("");
        setpassword.setText("");
        username.setText("");
        conf_password.setText("");
        setemail.setText("");
        date.setText("");
        month.setText("");
        year.setText("");
        address.setText("");
        x_coordinate.setText("");
        y_coordinate.setText("");
        
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void splcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_splcustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_splcustomerActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //on clicking log in
        new sign_in_page().setVisible(true);
        this.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //on clicking home
       
        this.setVisible(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_up_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_up_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_up_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sign_up_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelpassword;
    private javax.swing.JTextArea address;
    private javax.swing.JPasswordField conf_password;
    private javax.swing.JTextField date;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField month;
    private javax.swing.JTextField setemail;
    private javax.swing.JTextField setname;
    private javax.swing.JPasswordField setpassword;
    private javax.swing.JComboBox<String> splcustomer;
    private javax.swing.JTextField username;
    private javax.swing.JTextField x_coordinate;
    private javax.swing.JTextField y_coordinate;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
